### PR TITLE
card and filters models fixed

### LINKED ISSUE #61: Rework filters ComboBox and card models
ComboBox in CardsReferencePage as of now use their own model, that's prone to errors so it should be derived from TypeModel. 
Also TypeProxyModel should expose a property used to disable the Command Cards ComboBox.
Card data must be changed so that each card specifies only an ID as its type, thus the type name should be moved into a separate data structure mapping it to a certain ID. This should help for translations.

### PR DESCRIPTION
**Pull request by MaySantucci**
Fixed #61

### CODE REVIEW

File: src/models/cardsproxymodel.cpp [hunk 1]
```diff
@@ -44,16 +44,15 @@ bool CardsProxyModel::filterAcceptsRow(int source_row,
                   .toString();
 
   auto command =
-      model->data(createIndex(source_row, 0), CardsModel::Roles::Command)
-          .toString();
+      model->data(createIndex(source_row, 0), CardsModel::Roles::Command);
```
Comment (silvanocerza) [inline src/models/cardsproxymodel.cpp]: `data()` result must be converted to `int`.

File: src/models/commandlistmodel.cpp [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  case Roles::Key:
+    return row;
+  case Roles::Command:
+    return m_commands.value(row);
+  default:
+    return QVariant();
+  }
+}
+
+QString CommandListModel::getTypeFromIndex(int index) const {
```
Comment (silvanocerza) [inline src/models/commandlistmodel.cpp]: Remove this unused function.

File: src/models/commandlistmodel.h [hunk 3]
```diff
@@ -0,0 +1,28 @@
+#ifndef COMMANDLISTMODEL_H
+#define COMMANDLISTMODEL_H
+
+#include <QAbstractListModel>
+#include <QVector>
+
+class CommandListModel : public QAbstractListModel {
```
Comment (silvanocerza) [inline src/models/commandlistmodel.h]: Rename this `CommandComboBoxModel`.

File: src/models/typeproxymodel.cpp [hunk 4]
```diff
@@ -88,13 +97,14 @@ bool TypeProxyModel::filterAcceptsRow(int source_row,
   auto acceptRow = true;
 
   // Gets all roles that can be filtered
-  auto type = model->data(createIndex(source_row, 0), TypeModel::Roles::Type)
-                  .toString();
-  if (m_type == "All types" || m_type == type) {
+  auto type = model->data(createIndex(source_row, 0), TypeModel::Roles::Type);
```
Comment (silvanocerza) [inline src/models/typeproxymodel.cpp]: `data()` return value must be converted to `int`.

File: src/models/typeslistmodel.cpp [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+  case Roles::Key:
+    return row;
+  case Roles::Type:
+    return m_types.value(row);
+  default:
+    return QVariant();
+  }
+}
+
+QString TypesListModel::getTypeFromIndex(int index) const {
```
Comment (silvanocerza) [inline src/models/typeslistmodel.cpp]: Remove this unused function.

File: src/models/typeslistmodel.h [hunk 6]
```diff
@@ -0,0 +1,28 @@
+#ifndef TYPESLISTMODEL_H
+#define TYPESLISTMODEL_H
+
+#include <QAbstractListModel>
+#include <QVector>
+
+class TypesListModel : public QAbstractListModel {
```
Comment (silvanocerza) [inline src/models/typeslistmodel.h]: Rename to `TypeComboBoxModel`.

File: src/qml/Mysthea/Pages/DetailDelegate.qml [hunk 7]
```diff
@@ -13,8 +14,10 @@ Pane {
     background: null
 
     property string code: ""
```
Comment (silvanocerza) [inline src/qml/Mysthea/Pages/DetailDelegate.qml]: You could remove all this property and use only one property `model`.

**Review by silvanocerza — CHANGES_REQUESTED** [review]
See comments

File: src/qml/Mysthea/Pages/DetailDelegate.qml [hunk 8]
```diff
@@ -12,11 +13,7 @@ Pane {
     rightPadding: 20
     background: null
 
-    property string code: ""
-    property string type: ""
-    property string command: ""
-    property string image: ""
-    property string description: ""
+    property CardsModel card: null
```
Comment (silvanocerza) [inline src/qml/Mysthea/Pages/DetailDelegate.qml]: Remove this, it's not necessary after all.

**Review by silvanocerza — APPROVED** [review]
